### ISSUE TITLE
Missing OWL inference feature?

### ISSUE THREAD

**Issue by airballking** [knowrob/knowrob#194] opened 2018-03-07 13:34 UTC
@daniel86 as just discussed in person, there might be a missing OWL inference feature in KnowRob. The following two protege screenshots show the example that we just looked at on my PC:

Class hierarchy (with reasoner activated):
![protege_classes](https://user-images.githubusercontent.com/1560050/37094719-0f5a7e02-2214-11e8-803b-e552c4ba1cda.png)

Asserted Individual (with reasoner activated):
![protege_individual](https://user-images.githubusercontent.com/1560050/37094682-e9f2bd0a-2213-11e8-88fd-e3efd99e4cd8.png)

The protege reasoner correctly infers that ```Constant2``` also has the type ```ScalarQuantity```.

When asking Prolog, I only get the asserted and not the inferred type:

```prolog
?- owl_individual_of(I, semroco:'QuantifiedTerm').
I = 'http://knowrob.org/kb/semroco_test.owl#Constant2' ;
false.

?- owl_individual_of(I, semroco:'ScalarQuantity').
false.
```

**Comment by daniel86** [comment] 2024-04-02 12:50
The issue is related to an interface that has not been migrated to the C++ re-implementation of KnowRob. We won't fix remaining issues in the legacy code.

**Closed by daniel86** 2024-04-02 12:50 UTC
