### ISSUE TITLE
No permission to import comp_spatial:holds/2 into user (already imported from knowrob_language)

### ISSUE THREAD

**Issue by gheorghelisca** [knowrob/knowrob#112] opened 2016-08-03 13:11 UTC
- branch: robohow
- ERROR: /home/username/indigo/knowrob_ws/src/knowrob/comp_spatial/prolog/init.pl:40:
  import/1: No permission to import comp_spatial:holds/2 into user (already imported from knowrob_language)

**Comment by fairlight1337** [comment] 2016-08-03 13:34
Haven't seen this one before; while I know that it happens when you start the [longterm fetch and place scenario](https://github.com/code-iai/longterm_fetch_and_place), I don't quite see how it could be related. I don't get that error when starting the scenario.

Do you have more than one knowrob installation in your workspace?

**Comment by asilx** [comment] 2016-08-03 14:02
This error is caused by in-development predicates for the new knowrob language. In particular, holds predicate is both defined in knowrob_common and knowrob_cram packages. 

You can avoid this for now by commenting out the line 59 at knowrob_common/init.pl

**Comment by gheorghelisca** [comment] 2016-08-04 08:36
thanks a lot @asilx .. it seems that commenting out the line 59 at knowrob_common/init.pl did the trick

**Comment by daniel86** [comment] 2016-08-08 10:30
Should be fixed by https://github.com/knowrob/knowrob/pull/113

**Closed by daniel86** 2016-08-08 10:30 UTC
