### ISSUE TITLE
kb_project(...) fails with has_subevent

### ISSUE THREAD

**Issue by benjaminalt** [knowrob/knowrob#300] opened 2021-07-15 14:35 UTC
When trying to assert into the knowledge base that some action is a subevent of another action, the assertion fails:
```
?- kb_project([is_action(act_a), is_action(act_b)]).
true.
?- kb_project(has_subevent(act_a, act_b)).
false.
```
If I'm not mistaken, the second query should work and return true instead. Looking at the definition of `has_subevent`:
```
has_subevent(Event,Sub) +>
	(	is_action(Sub)  -> holds(Event,dul:hasConstituent,Sub)
	;	is_process(Sub) -> holds(Event,soma:hasPhase,Sub)
	;	is_state(Sub)   -> holds(Event,soma:hasPhase,Sub)
	;	fail
	).
```
`is_action(Sub)` should be true, so `holds(Event,dul:hasConstituent,Sub)` should be asserted into the knowledge base.

Interestingly, executing `holds(act_a,dul:hasConstituent,act_b)` by itself works.

**Comment by daniel86** [comment] 2024-04-02 12:48
The issue is related to an interface that has not been migrated to the C++ re-implementation of KnowRob. We won't fix remaining issues in the legacy code.

**Closed by daniel86** 2024-04-02 12:48 UTC
