### ISSUE TITLE
tf_set_pose/3 with current_scope/1 failure

### ISSUE THREAD

**Issue by McModknower** [knowrob/knowrob#367] opened 2023-02-20 11:29 UTC
Using tf_set_pose/3 with the scope returned by current_scope/1 results in ERROR:    Type error: \`float' expected, found \`=<(1676891447.4246414)' (a compound).

This seems to be caused by the fact that [tf_mem_set_pose/3](https://github.com/knowrob/knowrob/blob/c2ba5909dc60660b03bcea9bfd159717615afa51/src/ros/tf/tf.cpp#L133) and [tf_mng_store/3](https://github.com/knowrob/knowrob/blob/c2ba5909dc60660b03bcea9bfd159717615afa51/src/ros/tf/tf.cpp#L161) assume the `Since` value is a double,
and that [time_scope_data_/3](https://github.com/knowrob/knowrob/blob/c2ba5909dc60660b03bcea9bfd159717615afa51/src/lang/scope.pl#L143) (and in turn time_scope_data/2) only strip the operator from the `Since` value if it is an `=`.

Attached is a file to test it.
To test it,
1. download [scope_test.txt](https://github.com/knowrob/knowrob/files/10783887/scope_test.txt) to the src folder of knowrob and rename it to `scope_test.pl` (GitHub doesn't allow .pl files to be uploaded),
2. add `:- use_module('scope_test.pl').` at the end of the `__init__.pl`,
3. use `roslaunch knowrob knowrob` to start knowrob,
4. observe the output and see the 2 bold red lines starting with `ERROR:`

**Comment by daniel86** [comment] 2024-04-02 12:47
The issue is related to an interface that has not been migrated to the C++ re-implementation of KnowRob. We won't fix remaining issues in the legacy code.

However, the tf integration is still being worked on.

**Closed by daniel86** 2024-04-02 12:47 UTC
