### ISSUE TITLE
bson null in mongo response

### ISSUE THREAD

**Issue by McModknower** [knowrob/knowrob#368] opened 2023-03-24 14:19 UTC
I am currently developing something at https://github.com/SUTURO/suturo_knowledge/blob/feature/giskard-polling/suturo_knowledge/src/model/object/object_giskard_info.pl

This uses `kb_call(object_shape(...))` to get some data, including the shape term for an object.
When running the `giskard_test/0` predicate via the rosprolog commandline and when testing it in a bigger integrated setting, where the shape term should be `box(0.1, 0.2, 0.3)`, there is an error message (zero to three times, i don't know on what fact this number depends as it changes a lot) in the output of rosprolog: `WARN: unsupported array type '10'`. The output shows that the resulting shape term is missing as many numbers as there are error messages.

BSON type 10 is `null`. When i printed the json for the bson in one of these cases, i saw that there were `null`s in the term, but the numbers 0.1 0.2 and 0.3 also appeared, however at a different place.

I am currently working on creating a minimal example, but i haven't found one that is smaller yet.

**Comment by daniel86** [comment] 2024-04-02 12:48
The issue is related to an interface that has not been migrated to the C++ re-implementation of KnowRob. We won't fix remaining issues in the legacy code.

**Closed by daniel86** 2024-04-02 12:48 UTC
