### ISSUE TITLE
kb_project(...) throws exception for predicates whose second argument is not ground

### ISSUE THREAD

**Issue by benjaminalt** [knowrob/knowrob#299] opened 2021-07-14 14:41 UTC
When asserting facts into the knowledge base with `kb_project(...)`, I came across the problem that for some facts, `kb_project` throws the following error:
```
ERROR: Unhandled exception: mng_error(invalid_term(invalid type: (value)-string(v_10766)))
```
This happens for at least some binary predicates from _src/model/DUL.pl_ and _src/model/SOMA.pl_. It does not happen when the second argument is ground, and it also does not happen for unary predicates.

Example:
```
kb_project(executes_task(Action, Task)). % throws
kb_project(executes_task(Action, t)). % does not throw
kb_project(is_description(D)). % does not throw
kb_call(executes_task(Action, Task)). % does not throw
```
When I first make sure that Task is ground (i.e. by manually giving it an IRI before), kb_project does not throw:
```
kb_project([new_iri(Task, dul:'Task'),executes_task(Action,Task)]).  % <-- does not throw
```
Is this intended behavior, and I'm violating some implicit assumption here? The workaround is to give everything IRIs manually before calling kb_project, but it seems like this wasn't necessary with the old `tell` implementation (see https://github.com/seba90/cram/blob/cca9b08f872de83f6cd465e74c71ddfb0c438e39/cram_knowrob/cram_cloud_logger/src/neem-interface.pl).

**Comment by daniel86** [comment] 2024-04-02 12:49
The issue is related to an interface that has not been migrated to the C++ re-implementation of KnowRob. We won't fix remaining issues in the legacy code.

**Closed by daniel86** 2024-04-02 12:49 UTC
