### ISSUE TITLE
Is Knowrob team going to update http://wiki.ros.org/rosprolog to kinetic  ?

### ISSUE THREAD

**Issue by logicmoo** [knowrob/knowrob#108] opened 2016-07-17 06:29 UTC
Is Knowrob team going to update http://wiki.ros.org/rosprolog to kinetic  ?

**Comment by daniel86** [comment] 2016-08-08 13:22
Hi @logicmoo, yes I will work on that later this year.
Are there any issues you ran into?

**Comment by daniel86** [comment] 2017-03-01 11:14
Duplicate of https://github.com/knowrob/knowrob/issues/118

**Closed by daniel86** 2017-03-01 11:14 UTC
